import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SpacesNavBar from "./components/SpacesNavBar";
import styles from "./styles.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spaces",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <div className={inter.className}>
        <div className={styles.rootdiv}>
          <SpacesNavBar />
          {children}
        </div>
      </div>
    </section>
  );
}
